service: streameats
package: 
  individually: true
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  stage: dev
region: us-east-2
functions:
  api:
    handler: lambda.universal #lambda.universal
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true